# Generated by Django 5.2.5 on 2025-09-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_scale_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateitem",
            name="useAcknowledgement",
            field=models.TextField(default=False),
        ),
    ]
