# Generated by Django 5.2.5 on 2025-09-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ai_scale_app",
            "0002_rubric_acknowledgementform_rubricitem_template_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
