# Generated by Django 5.2.5 on 2025-09-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_scale_app", "0004_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rubric",
            name="isFinished",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AIUseScaleRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scaleName", models.CharField(max_length=120)),
                ("construct", models.CharField(blank=True, max_length=120)),
                ("dimension", models.CharField(blank=True, max_length=120)),
                ("subscale", models.CharField(blank=True, max_length=120)),
                ("itemText", models.TextField()),
                ("anchors", models.CharField(blank=True, max_length=200)),
                ("min", models.IntegerField(blank=True, null=True)),
                ("max", models.IntegerField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scaleName"], name="ai_scale_ap_scaleNa_472150_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scaleName", "itemText"),
                        name="unimelb_aiusescale_scale_item",
                    )
                ],
            },
        ),
    ]
