# Generated by Django 5.2.5 on 2025-09-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_scale_app", "0005_rubric_isfinished_aiusescalerow"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUseScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("N", "Level N"),
                            ("R1", "Level R1"),
                            ("R2", "Level R2"),
                            ("G", "Level G"),
                        ],
                        max_length=3,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("instructions", models.TextField(blank=True)),
                ("acknowledgement_required", models.BooleanField(default=False)),
                ("acknowledgement_text", models.TextField(blank=True)),
                ("acknowledgement_url", models.URLField(blank=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Optional hex (e.g., #FF6B6B)",
                        max_length=7,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Use Scale",
                "verbose_name_plural": "AI Use Scales",
                "ordering": ["position", "code"],
            },
        ),
        migrations.DeleteModel(
            name="AIUseScaleRow",
        ),
        migrations.AddIndex(
            model_name="aiusescale",
            index=models.Index(fields=["code"], name="ai_scale_ap_code_15d343_idx"),
        ),
    ]
