# Generated by Django 5.2.5 on 2025-09-11 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_scale_app", "0006_aiusescale_delete_aiusescalerow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acknowledgementform",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_scale_app.subject",
            ),
        ),
        migrations.AddField(
            model_name="rubric",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_scale_app.subject",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="semester",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="year",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="template",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_scale_app.subject",
            ),
        ),
        migrations.AlterField(
            model_name="rubricitem",
            name="aiUseScaleLevel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ai_scale_app.aiusescale",
            ),
        ),
        migrations.AlterField(
            model_name="templateitem",
            name="aiUseScaleLevel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ai_scale_app.aiusescale",
            ),
        ),
    ]
