# Generated by Django 5.2.5 on 2025-09-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_scale_app", "0007_acknowledgementform_subject_rubric_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rubric",
            name="version",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="template",
            name="version",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
